#!/usr/bin/env sh

# This is the configuration shell script, which will accomplish follow tasks
#  1. Get the crypto_folder associated with the usb_unlocker, and Vendor ID.
#     Move the helper function for doing encryption to a safer place.
#  2. Figure out what usb device to be the usb_unlocker. This is done by 
#     getting "signature" of the device, such as series number.
#  3. Install the module


MOD_NAME="usb_unlocker"
HELPER_PATH="/usr/local/src/crypto_helper"
DEVICE="usb_unlocker"

# step one
#  getting the key and the crypto_folder
CRYPTO_FOLDER=""
while [ ! -d CRYPTO_FOLDER ] 
do
    echo -n "Enter a valid crypto_folder:"
    read CRYPTO_FOLDER
done
cp $HELPER_PATH ./script/crypto_helper || (echo "failed copy helper to ${HELPER_PATH}"; exit)
#  get vendor id
VENDOR_ID=0
while [ ! VENDOR_ID -eq 0 ]
do 
    echo -n "Enter the vendor id of the usb device:"
    read VENDOR_ID
done

# step two.
# install the driver, and create a device node for user program to obtain
#  information about new usb device being plugged in. 
# Remove it after it is done
insmod ./module/${MOD_NAME}.ko mod_name=$MOD_NAME ioctl_on=1 \
    crypto_folder=$CRYPTO_FOLDER helper_path=$HELPER_PATH \
    VENDOR_ID = $VENDOR_ID || (echo "failed to install the module"; exit)
MAJOR=$(awk "\$2 == \"${module}\" {print \$1}" /proc/devices)
mknod /dev/${DEVICE} c $MAJOR 0 \
    || (echo "failed to make the node for dev with major: ${MAJOR}"; exit)

GROUP="staff"
grep -q '^staff:' /etc/group || GROUP="wheel"
chgrp $GROUP /dev/${DEVICE}
chmod 664 /dev/${DEVICE}

./script/wait_for_usb || (echo "something went wrong when waiting"; exit)



rm /dev/${DEVICE}
rmmod $MOD_NAME || (echo "can't remove the module?"; exit)

# step three
insmod ./module/${MOD_NAME}.ko mod_name=$MOD_NAME ioctl_on=0 \
    crypto_folder=$CRYPTO_FOLDER helper_path=$HELPER_PATH VENDOR_ID=$VENDOR_ID


